[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ansible/key.pem

[dev]
client-dev ansible_host=172.31.5.71

[test]
client-test ansible_host=172.31.5.136

[prod]
client-prod ansible_host=172.31.7.113

[dev:vars]
env=dev

[test:vars]
env=test

[prod:vars]
env=prod

[datascientest_app:children]
dev
test
prod

[serveurweb]
serveurweb1.datascientest.fr ansible_host=172.31.5.71

[serveurdatabase]
serveurdatabase1.datascientest.fr ansible_host=172.31.7.113

[production]
wordpress1.datascientest.fr ansible_host=172.31.5.136
